/* Generated By:JavaCC: Do not edit this line. ExpParserConstants.java */
package org.dflib.exp.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface ExpParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NULL = 35;
  /** RegularExpression Id. */
  int TRUE = 36;
  /** RegularExpression Id. */
  int FALSE = 37;
  /** RegularExpression Id. */
  int LONG_LITERAL = 38;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 39;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 40;
  /** RegularExpression Id. */
  int HEX_LITERAL = 41;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 42;
  /** RegularExpression Id. */
  int BINARY_LITERAL = 43;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 44;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 45;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 46;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 47;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 48;
  /** RegularExpression Id. */
  int HEX_DIGITS = 49;
  /** RegularExpression Id. */
  int ESCAPE = 50;
  /** RegularExpression Id. */
  int UNICODE_ESCAPE = 51;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 52;
  /** RegularExpression Id. */
  int STRING_LITERAL = 53;
  /** RegularExpression Id. */
  int IDENTIFIER = 54;
  /** RegularExpression Id. */
  int LETTER = 55;
  /** RegularExpression Id. */
  int PART_LETTER = 56;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"first\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"last\"",
    "\"min\"",
    "\"max\"",
    "\"if\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"!\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"between\"",
    "\"abs\"",
    "\"sum\"",
    "\"cumsum\"",
    "\"avg\"",
    "\"median\"",
    "\"int\"",
    "\"long\"",
    "\"float\"",
    "\"bool\"",
    "\"str\"",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "<LONG_LITERAL>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<BINARY_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<HEX_DIGITS>",
    "<ESCAPE>",
    "<UNICODE_ESCAPE>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
