name: 'build test deploy'

on:
  push:
    branches: [ '1.0.x' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        db: [ 'derby', 'mysql', 'postgresql' ]
        java: [ 11, 17, 21 ]

    steps:
      - name: Checkout...
        uses: actions/checkout@v4

      - name: Set up JDK...
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and test...
        run: mvn clean verify -ntp -U -P ${{ matrix.db }}

  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout...
      uses: actions/checkout@v4

    # this action exports env.POM_VERSION variable
    - name: Export Maven coordinates...
      uses: bootique-tools/export-maven-coordinates-action@v1

    - name: Set up JDK...
      uses: actions/setup-java@v4
      # skip this for the release versions
      if: contains(env.POM_VERSION, '-SNAPSHOT')
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'maven'

    - name: Deploy...
      # skip this for the release versions
      if: contains(env.POM_VERSION, '-SNAPSHOT')
      run: mvn clean source:jar javadoc:javadoc deploy -ntp -U -DskipTests --settings .github/workflows/maven_settings.xml
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
